---
- name: install docker and enable container logging to syslog
  hosts: local
  remote_user: root
  become: yes

  tasks:
  - name: update apt packages
    apt:
      update_cache: yes
  
  - name: install docker
    ansible.builtin.shell: curl -fssL https://get.docker.com -o get.docker.sh && sh get-docker.sh

  - name: create daemon.json and configure syslog
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
          "log-driver": "syslog"
        }

  - name: restart docker
    ansible.builtin.shell: systemctl daemon-reload && systemctl restart docker